"""sprint4_validation

Revision ID: 1932177095b0
Revises: 26e461161500
Create Date: 2026-05-18 09:25:44.060249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1932177095b0'
down_revision: Union[str, None] = '26e461161500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('monetary_count', sa.Integer(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('monetary_tolerance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_fiscal_period_id'), 'validation_runs', ['fiscal_period_id'], unique=False)
    op.create_table('validation_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_run_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('finding_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('register_code', sa.String(length=10), nullable=True),
    sa.Column('field_name', sa.String(length=60), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('cst', sa.String(length=3), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=True),
    sa.Column('operation_type', sa.String(length=30), nullable=True),
    sa.Column('efd_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reference_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('difference_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_findings_validation_run_id'), 'validation_findings', ['validation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_findings_validation_run_id'), table_name='validation_findings')
    op.drop_table('validation_findings')
    op.drop_index(op.f('ix_validation_runs_fiscal_period_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    # ### end Alembic commands ###
