"""sprint3_pdf_apuracao_reference

Revision ID: 26e461161500
Revises: 603bb2ec03cc
Create Date: 2026-05-18 09:14:38.280849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e461161500'
down_revision: Union[str, None] = '603bb2ec03cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_apuracao_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('extraction_error', sa.String(length=1000), nullable=True),
    sa.Column('average_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_apuracao_files_fiscal_period_id'), 'pdf_apuracao_files', ['fiscal_period_id'], unique=False)
    op.create_table('apuracao_reference_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('pdf_file_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('cst', sa.String(length=3), nullable=True),
    sa.Column('csosn', sa.String(length=3), nullable=True),
    sa.Column('cst_ipi', sa.String(length=2), nullable=True),
    sa.Column('aliquot', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('accounting_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('icms_base', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('icms_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('icms_st_base', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('icms_st_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ipi_base', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ipi_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('adjustment_code', sa.String(length=20), nullable=True),
    sa.Column('adjustment_description', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['pdf_apuracao_files.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apuracao_reference_values_company_id'), 'apuracao_reference_values', ['company_id'], unique=False)
    op.create_index(op.f('ix_apuracao_reference_values_fiscal_period_id'), 'apuracao_reference_values', ['fiscal_period_id'], unique=False)
    op.create_table('pdf_extracted_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pdf_file_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['pdf_apuracao_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pdf_file_id', 'page_number')
    )
    op.create_index(op.f('ix_pdf_extracted_pages_pdf_file_id'), 'pdf_extracted_pages', ['pdf_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_extracted_pages_pdf_file_id'), table_name='pdf_extracted_pages')
    op.drop_table('pdf_extracted_pages')
    op.drop_index(op.f('ix_apuracao_reference_values_fiscal_period_id'), table_name='apuracao_reference_values')
    op.drop_index(op.f('ix_apuracao_reference_values_company_id'), table_name='apuracao_reference_values')
    op.drop_table('apuracao_reference_values')
    op.drop_index(op.f('ix_pdf_apuracao_files_fiscal_period_id'), table_name='pdf_apuracao_files')
    op.drop_table('pdf_apuracao_files')
    # ### end Alembic commands ###
