"""efd_bloco_h_tables

Revision ID: 5280b073e93c
Revises: 7363700fbe80
Create Date: 2026-05-18 13:48:14.051385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5280b073e93c'
down_revision: Union[str, None] = '7363700fbe80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('efd_bloco_h005',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('dt_inv', sa.String(length=8), nullable=True),
    sa.Column('vl_inv', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('mot_inv', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_bloco_h005_efd_file_id'), 'efd_bloco_h005', ['efd_file_id'], unique=False)
    op.create_table('efd_bloco_h010',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('parent_h005_line_number', sa.Integer(), nullable=True),
    sa.Column('cod_item', sa.String(length=60), nullable=True),
    sa.Column('unid', sa.String(length=6), nullable=True),
    sa.Column('qtd', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('vl_unit', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('vl_item', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ind_prop', sa.String(length=1), nullable=True),
    sa.Column('cod_part', sa.String(length=60), nullable=True),
    sa.Column('txt_compl', sa.String(length=255), nullable=True),
    sa.Column('cod_cta', sa.String(length=255), nullable=True),
    sa.Column('vl_item_ir', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_bloco_h010_cod_item'), 'efd_bloco_h010', ['cod_item'], unique=False)
    op.create_index(op.f('ix_efd_bloco_h010_efd_file_id'), 'efd_bloco_h010', ['efd_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_efd_bloco_h010_efd_file_id'), table_name='efd_bloco_h010')
    op.drop_index(op.f('ix_efd_bloco_h010_cod_item'), table_name='efd_bloco_h010')
    op.drop_table('efd_bloco_h010')
    op.drop_index(op.f('ix_efd_bloco_h005_efd_file_id'), table_name='efd_bloco_h005')
    op.drop_table('efd_bloco_h005')
    # ### end Alembic commands ###
