"""sprint7_bloco_gk_fiscal_matrix

Revision ID: 55c392a9fc52
Revises: 5b210403a3df
Create Date: 2026-05-18 16:32:23.308022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c392a9fc52'
down_revision: Union[str, None] = '5b210403a3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfop_cst_full_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cfop', sa.String(length=10), nullable=False),
    sa.Column('cst_icms', sa.String(length=5), nullable=True),
    sa.Column('csosn', sa.String(length=5), nullable=True),
    sa.Column('operation_type', sa.String(length=10), nullable=True),
    sa.Column('rule_behavior', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('orientation_text', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('source_version', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfop_cst_full_rules_cfop'), 'cfop_cst_full_rules', ['cfop'], unique=False)
    op.create_table('cfop_ipi_cst_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cfop', sa.String(length=10), nullable=False),
    sa.Column('cst_ipi', sa.String(length=5), nullable=False),
    sa.Column('operation_type', sa.String(length=10), nullable=True),
    sa.Column('rule_behavior', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('orientation_text', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('source_version', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfop_ipi_cst_rules_cfop'), 'cfop_ipi_cst_rules', ['cfop'], unique=False)
    op.create_table('structural_obligation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('block_code', sa.String(length=5), nullable=False),
    sa.Column('obligation_type', sa.String(length=30), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('source_version', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('efd_bloco_g110',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('dt_ini', sa.String(length=8), nullable=True),
    sa.Column('dt_fin', sa.String(length=8), nullable=True),
    sa.Column('saldo_in_icms', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('som_parc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_trib_exp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ind_per_sai', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('icms_aprop', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('som_icms_oc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_bloco_g110_efd_file_id'), 'efd_bloco_g110', ['efd_file_id'], unique=False)
    op.create_table('efd_bloco_g125',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('parent_g110_line_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cod_ind_bem', sa.String(length=30), nullable=True),
    sa.Column('dt_mov', sa.String(length=8), nullable=True),
    sa.Column('tipo_mov', sa.String(length=5), nullable=True),
    sa.Column('vl_imob_icms_op', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_imob_icms_st', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_imob_icms_frt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_imob_icms_dif', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('num_parc', sa.Integer(), nullable=True),
    sa.Column('vl_parc_pass', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_bloco_g125_efd_file_id'), 'efd_bloco_g125', ['efd_file_id'], unique=False)
    op.create_table('efd_bloco_k100',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('dt_ini', sa.String(length=8), nullable=True),
    sa.Column('dt_fin', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_bloco_k100_efd_file_id'), 'efd_bloco_k100', ['efd_file_id'], unique=False)
    op.create_table('efd_bloco_k200',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('parent_k100_line_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('dt_est', sa.String(length=8), nullable=True),
    sa.Column('cod_item', sa.String(length=60), nullable=True),
    sa.Column('qtd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ind_est', sa.String(length=1), nullable=True),
    sa.Column('cod_part', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_bloco_k200_cod_item'), 'efd_bloco_k200', ['cod_item'], unique=False)
    op.create_index(op.f('ix_efd_bloco_k200_efd_file_id'), 'efd_bloco_k200', ['efd_file_id'], unique=False)
    op.add_column('companies', sa.Column('uses_ciap', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('requires_block_k', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('requires_inventory', sa.Boolean(), nullable=True))
    op.add_column('fiscal_periods', sa.Column('uses_ciap', sa.Boolean(), nullable=True))
    op.add_column('fiscal_periods', sa.Column('requires_block_k', sa.Boolean(), nullable=True))
    op.add_column('fiscal_periods', sa.Column('requires_inventory', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiscal_periods', 'requires_inventory')
    op.drop_column('fiscal_periods', 'requires_block_k')
    op.drop_column('fiscal_periods', 'uses_ciap')
    op.drop_column('companies', 'requires_inventory')
    op.drop_column('companies', 'requires_block_k')
    op.drop_column('companies', 'uses_ciap')
    op.drop_index(op.f('ix_efd_bloco_k200_efd_file_id'), table_name='efd_bloco_k200')
    op.drop_index(op.f('ix_efd_bloco_k200_cod_item'), table_name='efd_bloco_k200')
    op.drop_table('efd_bloco_k200')
    op.drop_index(op.f('ix_efd_bloco_k100_efd_file_id'), table_name='efd_bloco_k100')
    op.drop_table('efd_bloco_k100')
    op.drop_index(op.f('ix_efd_bloco_g125_efd_file_id'), table_name='efd_bloco_g125')
    op.drop_table('efd_bloco_g125')
    op.drop_index(op.f('ix_efd_bloco_g110_efd_file_id'), table_name='efd_bloco_g110')
    op.drop_table('efd_bloco_g110')
    op.drop_table('structural_obligation_rules')
    op.drop_index(op.f('ix_cfop_ipi_cst_rules_cfop'), table_name='cfop_ipi_cst_rules')
    op.drop_table('cfop_ipi_cst_rules')
    op.drop_index(op.f('ix_cfop_cst_full_rules_cfop'), table_name='cfop_cst_full_rules')
    op.drop_table('cfop_cst_full_rules')
    # ### end Alembic commands ###
