"""sprint6_correction_full

Revision ID: 5b210403a3df
Revises: ae42c9fbe1b6
Create Date: 2026-05-18 16:24:22.736736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b210403a3df'
down_revision: Union[str, None] = 'ae42c9fbe1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrected_files', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('corrected_files', sa.Column('fiscal_period_id', sa.UUID(), nullable=True))
    op.add_column('corrected_files', sa.Column('total_bytes', sa.BigInteger(), nullable=True))
    op.add_column('corrected_files', sa.Column('total_lines', sa.Integer(), nullable=True))
    op.add_column('corrected_files', sa.Column('generated_by', sa.UUID(), nullable=True))
    op.add_column('corrected_files', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('correction_logs', sa.Column('original_efd_file_id', sa.UUID(), nullable=True))
    op.add_column('correction_logs', sa.Column('action_type', sa.String(length=30), nullable=True))
    op.add_column('correction_logs', sa.Column('original_line', sa.Text(), nullable=True))
    op.add_column('correction_logs', sa.Column('new_line', sa.Text(), nullable=True))
    op.add_column('correction_logs', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('correction_logs', sa.Column('rule_code', sa.String(length=30), nullable=True))
    op.add_column('correction_logs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('correction_suggestions', sa.Column('validation_run_id', sa.UUID(), nullable=True))
    op.add_column('correction_suggestions', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('correction_suggestions', sa.Column('fiscal_period_id', sa.UUID(), nullable=True))
    op.add_column('correction_suggestions', sa.Column('suggestion_type', sa.String(length=20), nullable=False))
    op.add_column('correction_suggestions', sa.Column('action_type', sa.String(length=30), nullable=False))
    op.add_column('correction_suggestions', sa.Column('original_line', sa.Text(), nullable=True))
    op.add_column('correction_suggestions', sa.Column('suggested_line', sa.Text(), nullable=True))
    op.add_column('correction_suggestions', sa.Column('rule_code', sa.String(length=30), nullable=True))
    op.add_column('correction_suggestions', sa.Column('source', sa.String(length=60), nullable=True))
    op.add_column('correction_suggestions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_correction_suggestions_validation_run_id'), 'correction_suggestions', ['validation_run_id'], unique=False)
    op.create_foreign_key(None, 'correction_suggestions', 'validation_runs', ['validation_run_id'], ['id'])
    op.create_foreign_key(None, 'correction_suggestions', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'correction_suggestions', 'fiscal_periods', ['fiscal_period_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'correction_suggestions', type_='foreignkey')
    op.drop_constraint(None, 'correction_suggestions', type_='foreignkey')
    op.drop_constraint(None, 'correction_suggestions', type_='foreignkey')
    op.drop_index(op.f('ix_correction_suggestions_validation_run_id'), table_name='correction_suggestions')
    op.drop_column('correction_suggestions', 'updated_at')
    op.drop_column('correction_suggestions', 'source')
    op.drop_column('correction_suggestions', 'rule_code')
    op.drop_column('correction_suggestions', 'suggested_line')
    op.drop_column('correction_suggestions', 'original_line')
    op.drop_column('correction_suggestions', 'action_type')
    op.drop_column('correction_suggestions', 'suggestion_type')
    op.drop_column('correction_suggestions', 'fiscal_period_id')
    op.drop_column('correction_suggestions', 'company_id')
    op.drop_column('correction_suggestions', 'validation_run_id')
    op.drop_column('correction_logs', 'created_at')
    op.drop_column('correction_logs', 'rule_code')
    op.drop_column('correction_logs', 'risk_level')
    op.drop_column('correction_logs', 'new_line')
    op.drop_column('correction_logs', 'original_line')
    op.drop_column('correction_logs', 'action_type')
    op.drop_column('correction_logs', 'original_efd_file_id')
    op.drop_column('corrected_files', 'updated_at')
    op.drop_column('corrected_files', 'generated_by')
    op.drop_column('corrected_files', 'total_lines')
    op.drop_column('corrected_files', 'total_bytes')
    op.drop_column('corrected_files', 'fiscal_period_id')
    op.drop_column('corrected_files', 'company_id')
    # ### end Alembic commands ###
