"""sprint2_structured_records

Revision ID: 603bb2ec03cc
Revises: dbfa49049b5c
Create Date: 2026-05-18 09:07:17.392879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603bb2ec03cc'
down_revision: Union[str, None] = 'dbfa49049b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('efd_c190_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('parent_c100_line_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cst_icms', sa.String(length=3), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('aliq_icms', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('vl_opr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_bc_icms', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_icms', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_bc_icms_st', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_icms_st', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_red_bc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cod_obs', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_c190_analytics_efd_file_id'), 'efd_c190_analytics', ['efd_file_id'], unique=False)
    op.create_table('efd_e110_icms_apuracao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('vl_tot_debitos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_aj_debitos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_tot_aj_debitos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_estornos_cred', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_tot_creditos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_aj_creditos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_tot_aj_creditos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_estornos_deb', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_sld_credor_ant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_sld_apurado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_tot_ded', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_icms_recolher', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_sld_credor_transportar', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deb_esp', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_e110_icms_apuracao_efd_file_id'), 'efd_e110_icms_apuracao', ['efd_file_id'], unique=False)
    op.create_table('efd_e111_icms_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cod_aj_apur', sa.String(length=8), nullable=True),
    sa.Column('descr_compl_aj', sa.String(length=1024), nullable=True),
    sa.Column('vl_aj_apur', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_e111_icms_adjustments_efd_file_id'), 'efd_e111_icms_adjustments', ['efd_file_id'], unique=False)
    op.create_table('efd_e510_ipi_consolidation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('parent_e500_line_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('cst_ipi', sa.String(length=2), nullable=True),
    sa.Column('vl_cont_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_bc_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_e510_ipi_consolidation_efd_file_id'), 'efd_e510_ipi_consolidation', ['efd_file_id'], unique=False)
    op.create_table('efd_e520_ipi_apuracao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('parent_e500_line_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('vl_sd_ant_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_deb_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_cred_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_od_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_oc_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_sc_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_sd_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_e520_ipi_apuracao_efd_file_id'), 'efd_e520_ipi_apuracao', ['efd_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_efd_e520_ipi_apuracao_efd_file_id'), table_name='efd_e520_ipi_apuracao')
    op.drop_table('efd_e520_ipi_apuracao')
    op.drop_index(op.f('ix_efd_e510_ipi_consolidation_efd_file_id'), table_name='efd_e510_ipi_consolidation')
    op.drop_table('efd_e510_ipi_consolidation')
    op.drop_index(op.f('ix_efd_e111_icms_adjustments_efd_file_id'), table_name='efd_e111_icms_adjustments')
    op.drop_table('efd_e111_icms_adjustments')
    op.drop_index(op.f('ix_efd_e110_icms_apuracao_efd_file_id'), table_name='efd_e110_icms_apuracao')
    op.drop_table('efd_e110_icms_apuracao')
    op.drop_index(op.f('ix_efd_c190_analytics_efd_file_id'), table_name='efd_c190_analytics')
    op.drop_table('efd_c190_analytics')
    # ### end Alembic commands ###
