"""add_c100_docs

Revision ID: 6916b9a7a0b0
Revises: 81d91dde2f7f
Create Date: 2026-05-18 09:46:45.882026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6916b9a7a0b0'
down_revision: Union[str, None] = '81d91dde2f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('efd_c100_docs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('ind_oper', sa.String(length=1), nullable=True),
    sa.Column('ind_emit', sa.String(length=1), nullable=True),
    sa.Column('cod_part', sa.String(length=60), nullable=True),
    sa.Column('cod_mod', sa.String(length=2), nullable=True),
    sa.Column('cod_sit', sa.String(length=2), nullable=True),
    sa.Column('ser', sa.String(length=4), nullable=True),
    sa.Column('num_doc', sa.String(length=9), nullable=True),
    sa.Column('chv_nfe', sa.String(length=44), nullable=True),
    sa.Column('dt_doc', sa.String(length=8), nullable=True),
    sa.Column('dt_e_s', sa.String(length=8), nullable=True),
    sa.Column('vl_doc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_desc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_merc', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_frt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_seg', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_out_da', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_bc_icms', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_icms', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_bc_icms_st', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_icms_st', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_ipi', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_pis', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vl_cofins', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_c100_docs_efd_file_id'), 'efd_c100_docs', ['efd_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_efd_c100_docs_efd_file_id'), table_name='efd_c100_docs')
    op.drop_table('efd_c100_docs')
    # ### end Alembic commands ###
