"""efd_bloco0_tables

Revision ID: 7363700fbe80
Revises: f07151a67e37
Create Date: 2026-05-18 11:04:37.618130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7363700fbe80'
down_revision: Union[str, None] = 'f07151a67e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('efd_bloco0_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cod_item', sa.String(length=60), nullable=True),
    sa.Column('descr_item', sa.String(length=200), nullable=True),
    sa.Column('cod_barra', sa.String(length=14), nullable=True),
    sa.Column('cod_ant_item', sa.String(length=60), nullable=True),
    sa.Column('unid_inv', sa.String(length=6), nullable=True),
    sa.Column('tipo_item', sa.String(length=2), nullable=True),
    sa.Column('cod_ncm', sa.String(length=8), nullable=True),
    sa.Column('ex_ipi', sa.String(length=3), nullable=True),
    sa.Column('cod_gen', sa.String(length=2), nullable=True),
    sa.Column('cod_lst', sa.String(length=5), nullable=True),
    sa.Column('aliq_icms', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cest', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_bloco0_items_cod_item'), 'efd_bloco0_items', ['cod_item'], unique=False)
    op.create_index(op.f('ix_efd_bloco0_items_efd_file_id'), 'efd_bloco0_items', ['efd_file_id'], unique=False)
    op.create_table('efd_bloco0_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cod_part', sa.String(length=60), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cod_pais', sa.String(length=5), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('ie', sa.String(length=14), nullable=True),
    sa.Column('cod_mun', sa.String(length=7), nullable=True),
    sa.Column('suframa', sa.String(length=9), nullable=True),
    sa.Column('end', sa.String(length=60), nullable=True),
    sa.Column('num', sa.String(length=10), nullable=True),
    sa.Column('compl', sa.String(length=60), nullable=True),
    sa.Column('bairro', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_bloco0_parts_cod_part'), 'efd_bloco0_parts', ['cod_part'], unique=False)
    op.create_index(op.f('ix_efd_bloco0_parts_efd_file_id'), 'efd_bloco0_parts', ['efd_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_efd_bloco0_parts_efd_file_id'), table_name='efd_bloco0_parts')
    op.drop_index(op.f('ix_efd_bloco0_parts_cod_part'), table_name='efd_bloco0_parts')
    op.drop_table('efd_bloco0_parts')
    op.drop_index(op.f('ix_efd_bloco0_items_efd_file_id'), table_name='efd_bloco0_items')
    op.drop_index(op.f('ix_efd_bloco0_items_cod_item'), table_name='efd_bloco0_items')
    op.drop_table('efd_bloco0_items')
    # ### end Alembic commands ###
