"""sprint_correction

Revision ID: 81d91dde2f7f
Revises: 1932177095b0
Create Date: 2026-05-18 09:38:20.062188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d91dde2f7f'
down_revision: Union[str, None] = '1932177095b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrected_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_efd_file_id', sa.UUID(), nullable=False),
    sa.Column('generated_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('applied_suggestions_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['original_efd_file_id'], ['efd_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correction_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('register_code', sa.String(length=10), nullable=False),
    sa.Column('field_index', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('original_value', sa.String(length=100), nullable=True),
    sa.Column('suggested_value', sa.String(length=100), nullable=False),
    sa.Column('suggestion_reason', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.String(length=255), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efd_file_id'], ['efd_files.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['validation_findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_suggestions_efd_file_id'), 'correction_suggestions', ['efd_file_id'], unique=False)
    op.create_index(op.f('ix_correction_suggestions_finding_id'), 'correction_suggestions', ['finding_id'], unique=False)
    op.create_table('correction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('corrected_file_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('register_code', sa.String(length=10), nullable=False),
    sa.Column('field_index', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('original_value', sa.String(length=100), nullable=True),
    sa.Column('applied_value', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_file_id'], ['corrected_files.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['correction_suggestions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_logs_corrected_file_id'), 'correction_logs', ['corrected_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correction_logs_corrected_file_id'), table_name='correction_logs')
    op.drop_table('correction_logs')
    op.drop_index(op.f('ix_correction_suggestions_finding_id'), table_name='correction_suggestions')
    op.drop_index(op.f('ix_correction_suggestions_efd_file_id'), table_name='correction_suggestions')
    op.drop_table('correction_suggestions')
    op.drop_table('corrected_files')
    # ### end Alembic commands ###
