"""pr_adjustments_e112_e113

Revision ID: a5d302597c02
Revises: 6916b9a7a0b0
Create Date: 2026-05-18 10:12:05.339517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d302597c02'
down_revision: Union[str, None] = '6916b9a7a0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('efd_e112_adjustment_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('parent_e111_line_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('num_da', sa.String(length=255), nullable=True),
    sa.Column('num_proc', sa.String(length=60), nullable=True),
    sa.Column('ind_proc', sa.String(length=1), nullable=True),
    sa.Column('proc', sa.String(length=255), nullable=True),
    sa.Column('txt_compl', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_e112_adjustment_info_efd_file_id'), 'efd_e112_adjustment_info', ['efd_file_id'], unique=False)
    op.create_table('efd_e113_adjustment_docs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('parent_e111_line_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('cod_part', sa.String(length=60), nullable=True),
    sa.Column('cod_mod', sa.String(length=2), nullable=True),
    sa.Column('ser', sa.String(length=4), nullable=True),
    sa.Column('sub', sa.String(length=3), nullable=True),
    sa.Column('num_doc', sa.String(length=9), nullable=True),
    sa.Column('dt_doc', sa.String(length=8), nullable=True),
    sa.Column('cod_item', sa.String(length=60), nullable=True),
    sa.Column('chv_doc_e', sa.String(length=44), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efd_e113_adjustment_docs_efd_file_id'), 'efd_e113_adjustment_docs', ['efd_file_id'], unique=False)
    op.create_table('pr_adjustment_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('adjustment_text', sa.Text(), nullable=True),
    sa.Column('requires_e112', sa.Boolean(), nullable=False),
    sa.Column('requires_e113', sa.Boolean(), nullable=False),
    sa.Column('optional_e112', sa.Boolean(), nullable=False),
    sa.Column('optional_e113', sa.Boolean(), nullable=False),
    sa.Column('page_ref', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_adjustment_codes_code'), 'pr_adjustment_codes', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pr_adjustment_codes_code'), table_name='pr_adjustment_codes')
    op.drop_table('pr_adjustment_codes')
    op.drop_index(op.f('ix_efd_e113_adjustment_docs_efd_file_id'), table_name='efd_e113_adjustment_docs')
    op.drop_table('efd_e113_adjustment_docs')
    op.drop_index(op.f('ix_efd_e112_adjustment_info_efd_file_id'), table_name='efd_e112_adjustment_info')
    op.drop_table('efd_e112_adjustment_info')
    # ### end Alembic commands ###
