"""sprint5_pr_adjustment_full

Revision ID: ae42c9fbe1b6
Revises: 5280b073e93c
Create Date: 2026-05-18 14:34:09.393647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae42c9fbe1b6'
down_revision: Union[str, None] = '5280b073e93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pr_adjustment_import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('source_version', sa.String(length=30), nullable=True),
    sa.Column('imported_by', sa.UUID(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('records_total', sa.Integer(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_adjustment_validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_run_id', sa.UUID(), nullable=False),
    sa.Column('efd_file_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=True),
    sa.Column('register_code', sa.String(length=10), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('adjustment_code', sa.String(length=20), nullable=True),
    sa.Column('adjustment_table_type', sa.String(length=30), nullable=True),
    sa.Column('pr_adjustment_code_id', sa.UUID(), nullable=True),
    sa.Column('validation_rule_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('requires_e112', sa.Boolean(), nullable=True),
    sa.Column('has_e112', sa.Boolean(), nullable=True),
    sa.Column('requires_e113', sa.Boolean(), nullable=True),
    sa.Column('has_e113', sa.Boolean(), nullable=True),
    sa.Column('requires_process', sa.Boolean(), nullable=True),
    sa.Column('has_process', sa.Boolean(), nullable=True),
    sa.Column('requires_fiscal_document', sa.Boolean(), nullable=True),
    sa.Column('has_fiscal_document', sa.Boolean(), nullable=True),
    sa.Column('requires_auxiliary_ie', sa.Boolean(), nullable=True),
    sa.Column('has_auxiliary_ie', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_adjustment_validation_results_efd_file_id'), 'pr_adjustment_validation_results', ['efd_file_id'], unique=False)
    op.create_index(op.f('ix_pr_adjustment_validation_results_validation_run_id'), 'pr_adjustment_validation_results', ['validation_run_id'], unique=False)
    op.add_column('companies', sa.Column('auxiliary_state_registration', sa.String(length=50), nullable=True))
    op.add_column('fiscal_periods', sa.Column('uses_auxiliary_ie', sa.Boolean(), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('table_type', sa.String(length=30), nullable=False, server_default='ajuste_apuracao'))
    op.add_column('pr_adjustment_codes', sa.Column('short_description', sa.String(length=100), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('register_expected', sa.String(length=10), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('apuracao_type', sa.String(length=30), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('adjustment_nature', sa.String(length=30), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('operation_scope', sa.String(length=100), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('requires_fiscal_document', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('pr_adjustment_codes', sa.Column('requires_process', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('pr_adjustment_codes', sa.Column('requires_auxiliary_ie', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('pr_adjustment_codes', sa.Column('requires_item', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('pr_adjustment_codes', sa.Column('requires_participant', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('pr_adjustment_codes', sa.Column('valid_from', sa.Date(), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('valid_to', sa.Date(), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('orientation_text', sa.Text(), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('source_name', sa.String(length=100), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('source_version', sa.String(length=30), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('import_batch_id', sa.UUID(), nullable=True))
    op.add_column('pr_adjustment_codes', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_pr_adjustment_codes_code'), table_name='pr_adjustment_codes')
    op.create_index(op.f('ix_pr_adjustment_codes_code'), 'pr_adjustment_codes', ['code'], unique=False)
    op.create_index('ix_pr_adjustment_codes_code_table_type', 'pr_adjustment_codes', ['code', 'table_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pr_adjustment_codes_code_table_type', table_name='pr_adjustment_codes')
    op.drop_index(op.f('ix_pr_adjustment_codes_code'), table_name='pr_adjustment_codes')
    op.create_index(op.f('ix_pr_adjustment_codes_code'), 'pr_adjustment_codes', ['code'], unique=True)
    op.drop_column('pr_adjustment_codes', 'updated_at')
    op.drop_column('pr_adjustment_codes', 'import_batch_id')
    op.drop_column('pr_adjustment_codes', 'source_version')
    op.drop_column('pr_adjustment_codes', 'source_url')
    op.drop_column('pr_adjustment_codes', 'source_name')
    op.drop_column('pr_adjustment_codes', 'orientation_text')
    op.drop_column('pr_adjustment_codes', 'valid_to')
    op.drop_column('pr_adjustment_codes', 'valid_from')
    op.drop_column('pr_adjustment_codes', 'requires_participant')
    op.drop_column('pr_adjustment_codes', 'requires_item')
    op.drop_column('pr_adjustment_codes', 'requires_auxiliary_ie')
    op.drop_column('pr_adjustment_codes', 'requires_process')
    op.drop_column('pr_adjustment_codes', 'requires_fiscal_document')
    op.drop_column('pr_adjustment_codes', 'operation_scope')
    op.drop_column('pr_adjustment_codes', 'adjustment_nature')
    op.drop_column('pr_adjustment_codes', 'apuracao_type')
    op.drop_column('pr_adjustment_codes', 'register_expected')
    op.drop_column('pr_adjustment_codes', 'short_description')
    op.drop_column('pr_adjustment_codes', 'table_type')
    op.drop_column('fiscal_periods', 'uses_auxiliary_ie')
    op.drop_column('companies', 'auxiliary_state_registration')
    op.drop_index(op.f('ix_pr_adjustment_validation_results_validation_run_id'), table_name='pr_adjustment_validation_results')
    op.drop_index(op.f('ix_pr_adjustment_validation_results_efd_file_id'), table_name='pr_adjustment_validation_results')
    op.drop_table('pr_adjustment_validation_results')
    op.drop_table('pr_adjustment_import_batches')
    # ### end Alembic commands ###
