"""sprint8_period_analytics

Revision ID: c6b371db1d3d
Revises: 55c392a9fc52
Create Date: 2026-05-18 18:38:38.500109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6b371db1d3d'
down_revision: Union[str, None] = '55c392a9fc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_period_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('event_title', sa.String(length=255), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=40), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_period_events_company_id'), 'fiscal_period_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_fiscal_period_events_fiscal_period_id'), 'fiscal_period_events', ['fiscal_period_id'], unique=False)
    op.create_table('fiscal_period_risk_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('info_count', sa.Integer(), nullable=False),
    sa.Column('open_suggestions_count', sa.Integer(), nullable=False),
    sa.Column('approved_suggestions_count', sa.Integer(), nullable=False),
    sa.Column('rejected_suggestions_count', sa.Integer(), nullable=False),
    sa.Column('corrected_files_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_period_risk_snapshots_company_id'), 'fiscal_period_risk_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_fiscal_period_risk_snapshots_fiscal_period_id'), 'fiscal_period_risk_snapshots', ['fiscal_period_id'], unique=False)
    op.create_table('report_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('package_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_packages_fiscal_period_id'), 'report_packages', ['fiscal_period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_packages_fiscal_period_id'), table_name='report_packages')
    op.drop_table('report_packages')
    op.drop_index(op.f('ix_fiscal_period_risk_snapshots_fiscal_period_id'), table_name='fiscal_period_risk_snapshots')
    op.drop_index(op.f('ix_fiscal_period_risk_snapshots_company_id'), table_name='fiscal_period_risk_snapshots')
    op.drop_table('fiscal_period_risk_snapshots')
    op.drop_index(op.f('ix_fiscal_period_events_fiscal_period_id'), table_name='fiscal_period_events')
    op.drop_index(op.f('ix_fiscal_period_events_company_id'), table_name='fiscal_period_events')
    op.drop_table('fiscal_period_events')
    # ### end Alembic commands ###
