"""cfop_cst_rules

Revision ID: f07151a67e37
Revises: db1763dcdc81
Create Date: 2026-05-18 10:53:47.104382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07151a67e37'
down_revision: Union[str, None] = 'db1763dcdc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfop_cst_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cfop_pattern', sa.String(length=5), nullable=False),
    sa.Column('operation_type', sa.String(length=10), nullable=False),
    sa.Column('allowed_cst', sa.String(length=200), nullable=True),
    sa.Column('disallowed_cst', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfop_cst_rules_cfop_pattern'), 'cfop_cst_rules', ['cfop_pattern'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cfop_cst_rules_cfop_pattern'), table_name='cfop_cst_rules')
    op.drop_table('cfop_cst_rules')
    # ### end Alembic commands ###
